### ISSUE TITLE
`splitpath` and URL parameters

### ISSUE THREAD

**Issue by fonsp** [JuliaWeb/URIs.jl#14]
1. `splitpath` does not handle URL parameters correctly
2. `splitpath` does not accept a `URI`

```julia
julia> URIs.splitpath("/a/b?c=d")
1-element Array{String,1}:
 "a"

julia> URIs.splitpath("/a/b")
2-element Array{String,1}:
 "a"
 "b"

julia> URIs.splitpath(URI("/a/b?c=d"))
ERROR: MethodError: no method matching splitpath(::URI)
Closest candidates are:
  splitpath(::AbstractString) at /Users/fons/.julia/packages/URIs/1jrj1/src/URIs.jl:382
Stacktrace:
 [1] top-level scope at REPL[9]:1

julia> URIs.splitpath(URI("/a/b?c=d").path)
2-element Array{String,1}:
 "a"
 "b"
```

URIs.jl v1.1.0

**Comment by fonsp** [comment]
Calling `splitpath` directly on the request target is recommended in the HTTP docs: https://juliaweb.github.io/HTTP.jl/stable/public_interface/#HTTP.Handlers

**Comment by c42f** [comment]
Does #16 fix this for you?

> Does not handle URL parameters correctly

TBH I'm not quite sure we should expect it to split off the query and fragment here (that's handled by the `URI` parser). But it seems `splitpath` was originally designed to do this, and it's fairly harmless so I fixed that as well.

**Comment by fonsp** [comment]
Awesome! That addresses all my problems.

I think splitting off the query is the right choice! To me, `splitpath` is to find out "where it is", analogously to `Base.splitdir`, and the query and fragment don't carry this information.

**Comment by c42f** [comment]
> To me, splitpath is to find out "where it is", analogously to Base.splitdir, and the query and fragment don't carry this information.

Yes definitely. But what I'm slightly unsure about here is why you'd have the path and query/fragment in `str`, but not just use `parse(URI, str)` to parse it as a relative URI, then use `splitpath()` from there — it seems a little odd to be doing extra parsing work in `splitpath()` when that's arguably the job of `parse(URI, str)` instead.  (Also, `splitpath()` will never work on absolute URIs provided as strings.)

But anyway I can see that it might be convenient and it seems fairly harmless, so I think we can just go with dropping the query and fragment.
