### ISSUE TITLE
Method invalidation

### ISSUE THREAD

**Issue by tlienart** [JuliaWeb/URIs.jl#15]
In playing with SnoopCompile, there's a method invalidation 

```
 inserting joinpath(uri::URIs.URI, parts::String...) in URIs at /Users/tlienart/.julia/packages/URIs/1jrj1/src/URIs.jl:466 invalidated:
   mt_backedges: 1: signature Tuple{typeof(joinpath), Any, String} triggered MethodInstance for Artifacts.jointail(::Any, ::String) (0 children)
```

I'm not quite savvy enough to know what to do about this though (see also https://github.com/timholy/SnoopCompile.jl/issues/210)

**Comment by tlienart** [comment]
I'm closing this as Tim basically told me invalidations with 0 children are effectively not very useful :)

**Comment by c42f** [comment]
Thanks, the best type of issue is the issue which is closed before you even get to it :sweat_smile: :laughing:
