### ISSUE TITLE
Public API for URIs.jl

### ISSUE THREAD

**Issue by c42f** [JuliaWeb/URIs.jl#2]
Are we happy with the API which is exported from this package, and is there public API which should be documented but which is not exported?

Not being the author of this code, it's not entirely clear to me where the boundaries lie but I'm happy to do some legwork. @quinnj any thoughts?

At least we should document the exports (`queryparams`, `absuri`, `escapepath`) which are currently undocumented.

Also pinging @samoconnor on the off chance he's around and interested in commenting on some old code of his :-)

Of course, this doesn't block a 0.1 release. We should probably just get that ball rolling asap.

**Comment by quinnj** [comment]
Yeah, I think documenting those and the keeping the existing exports sounds good to me. Let's just make the first release 1.0; this code has been around long enough that I'm comfortable w/ that and I like having all 3 semver numbers to work with.

**Comment by c42f** [comment]
I went through the export list and started documenting a bit. I feel like `resource` is not a great match for exporting: it seems a very generic name for quite specific functionality. (`escapepath` and to a lesser extent `queryparams` are also not ideal from that point of view.)

Actually it `resource` seems to be HTTP-related functionality (Defined in HTTP/1.1 https://tools.ietf.org/html/rfc7230#section-5.3), so perhaps it makes sense to just remove it from here and leave it in HTTP.jl.

**Comment by quinnj** [comment]
Yeah, I agree that can live in HTTP.jl

**Comment by c42f** [comment]
Cool, I'll put a PR up for that and merge it once CI passes.  Then try to register a 1.0

**Comment by c42f** [comment]
Done, and I've kicked off registration https://github.com/JuliaRegistries/General/pull/22989
