### ISSUE TITLE
ERROR: MethodError: no method matching _bytes(::String15)

### ISSUE THREAD

**Issue by anandijain** [JuliaWeb/URIs.jl#42]
I guess it makes sense that you may not want to implicitly convert S15->String, but for someone that may not care what a String15 is, (like it being read from a CSV), it's a confusing error.

Should the fix be defining `_bytes(s::AbstractString) = _bytes(String(s))`? Not sure if that's right

**Comment by quinnj** [comment]
Thanks for the report; fix is up: https://github.com/JuliaWeb/URIs.jl/pull/48
